"""Title field added in the database model

Revision ID: 9f8ef78c6280
Revises: d2c1a65d0b2c
Create Date: 2025-12-08 11:08:33.381940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8ef78c6280'
down_revision: Union[str, Sequence[str], None] = 'd2c1a65d0b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('databases', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('databases', 'title')
    # ### end Alembic commands ###
