"""Title field added in the database model

Revision ID: d2c1a65d0b2c
Revises: da17529d257b
Create Date: 2025-12-08 11:04:53.495178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c1a65d0b2c'
down_revision: Union[str, Sequence[str], None] = 'da17529d257b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_dashboards', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_dashboards', 'title')
    # ### end Alembic commands ###
