"""Added new fields in the dashboard

Revision ID: da17529d257b
Revises: c186e7743f84
Create Date: 2025-12-04 14:28:14.493220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da17529d257b'
down_revision: Union[str, Sequence[str], None] = 'c186e7743f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_dashboards', sa.Column('db_id', sa.Integer(), nullable=True))
    op.add_column('saved_dashboards', sa.Column('db_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_dashboards', 'db_name')
    op.drop_column('saved_dashboards', 'db_id')
    # ### end Alembic commands ###
