"""add schema in DB tbl

Revision ID: f0cd15828906
Revises: fbf661eb1de4
Create Date: 2026-01-05 10:37:23.342990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cd15828906'
down_revision: Union[str, Sequence[str], None] = 'fbf661eb1de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('databases', sa.Column('schema', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('databases', 'schema')
    # ### end Alembic commands ###
